const carBrands = [
    { name: "9ff", country: "Alemania", logo: "./logos/9ff-logo.png" },
    { name: "Abadal", country: "España", logo: "./logos/abadal-logo.png" },
    { name: "Abarth", country: "Italia", logo: "./logos/abarth-logo.png" },
    { name: "Abbott-Detroit", country: "Estados Unidos", logo: "./logos/abbott-detroit-logo.png" },
    { name: "ABT Sportsline", country: "Alemania", logo: "./logos/abt-sportsline-logo.png" },
    { name: "AC", country: "Reino Unido", logo: "./logos/ac-logo.png" },
    { name: "Acura", country: "Japón", logo: "./logos/acura-logo.png" },
    { name: "Aiways", country: "China", logo: "./logos/aiways-logo.png" },
    { name: "Aixam", country: "Francia", logo: "./logos/aixam-logo.png" },
    { name: "Alfa Romeo", country: "Italia", logo: "./logos/alfa-romeo-logo.png" },
    { name: "Alpina", country: "Alemania", logo: "./logos/alpina-logo.png" },
    { name: "Alpine", country: "Francia", logo: "./logos/alpine-logo.png" },
    { name: "Alta", country: "Grecia", logo: "./logos/alta-logo.png" },
    { name: "Alvis", country: "Reino Unido", logo: "./logos/alvis-logo.png" },
    { name: "American Motors", country: "Estados Unidos", logo: "./logos/american-motors-logo.png" },
    { name: "Apollo", country: "Alemania", logo: "./logos/apollo-logo.png" },
    { name: "Arash", country: "Reino Unido", logo: "./logos/arash-logo.png" },
    { name: "Arcfox", country: "China", logo: "./logos/arcfox-logo.png" },
    { name: "Ariel", country: "Reino Unido", logo: "./logos/ariel-logo.png" },
    { name: "ARO", country: "Rumania", logo: "./logos/aro-logo.png" },
    { name: "Arrinera", country: "Polonia", logo: "./logos/arrinera-logo.png" },
    { name: "Arrival", country: "Reino Unido", logo: "./logos/arrival-logo.png" },
    { name: "Artega", country: "Alemania", logo: "./logos/artega-logo.png" },
    { name: "Ascari", country: "Reino Unido", logo: "./logos/ascari-logo.png" },
    { name: "Askam", country: "Turquía", logo: "./logos/askam-logo.png" },
    { name: "Aspark", country: "Japón", logo: "./logos/aspark-logo.png" },
    { name: "Aston Martin", country: "Reino Unido", logo: "./logos/aston-martin-logo.png" },
    { name: "Atalanta Motors", country: "Reino Unido", logo: "./logos/atalanta-motors-logo.png" },
    { name: "Auburn", country: "Estados Unidos", logo: "./logos/auburn-logo.png" },
    { name: "Audi", country: "Alemania", logo: "./logos/audi-logo.png" },
    { name: "Audi Sport", country: "Alemania", logo: "./logos/audi-sport-logo.png" },
    { name: "Austin", country: "Reino Unido", logo: "./logos/austin-logo.png" },
    { name: "Autobacs", country: "Japón", logo: "./logos/autobacs-logo.png" },
    { name: "Autobianchi", country: "Italia", logo: "./logos/autobianchi-logo.png" },
    { name: "Axon", country: "Reino Unido", logo: "./logos/axon-logo.png" },
    { name: "BAC", country: "Reino Unido", logo: "./logos/bac-logo.png" },
    { name: "BAIC", country: "China", logo: "./logos/baic-logo.png" },
    { name: "Baojun", country: "China", logo: "./logos/baojun-logo.png" },
    { name: "Beiben", country: "China", logo: "./logos/beiben-logo.png" },
    { name: "Bentley", country: "Reino Unido", logo: "./logos/bentley-logo.png" },
    { name: "Berkeley", country: "Reino Unido", logo: "./logos/berkeley-logo.png" },
    { name: "Berliet", country: "Francia", logo: "./logos/berliet-logo.png" },
    { name: "Bertone", country: "Italia", logo: "./logos/bertone-logo.png" },
    { name: "Bestune", country: "China", logo: "./logos/bestune-logo.png" },
    { name: "BharatBenz", country: "India", logo: "./logos/bharatbenz-logo.png" },
    { name: "Bitter", country: "Alemania", logo: "./logos/bitter-logo.png" },
    { name: "Bizzarrini", country: "Italia", logo: "./logos/bizzarrini-logo.png" },
    { name: "BMW", country: "Alemania", logo: "./logos/bmw-logo.png" },
    { name: "BMW M", country: "Alemania", logo: "./logos/bmw-m-logo.png" },
    { name: "Borgward", country: "Alemania", logo: "./logos/borgward-logo.png" },
    { name: "Bowler", country: "Reino Unido", logo: "./logos/bowler-logo.png" },
    { name: "Brabus", country: "Alemania", logo: "./logos/brabus-logo.png" },
    { name: "Brammo", country: "Estados Unidos", logo: "./logos/brammo-logo.png" },
    { name: "Brilliance", country: "China", logo: "./logos/brilliance-logo.png" },
    { name: "Bristol", country: "Reino Unido", logo: "./logos/bristol-logo.png" },
    { name: "Brooke", country: "Reino Unido", logo: "./logos/brooke-logo.png" },
    { name: "Bufori", country: "Malasia", logo: "./logos/bufori-logo.png" },
    { name: "Bugatti", country: "Francia", logo: "./logos/bugatti-logo.png" },
    { name: "Buick", country: "Estados Unidos", logo: "./logos/buick-logo.png" },
    { name: "BYD", country: "China", logo: "./logos/byd-logo.png" },
    { name: "Byton", country: "China", logo: "./logos/byton-logo.png" },
    { name: "Cadillac", country: "Estados Unidos", logo: "./logos/cadillac-logo.png" },
    { name: "CAMC", country: "China", logo: "./logos/camc-logo.png" },
    { name: "Canoo", country: "Estados Unidos", logo: "./logos/canoo-logo.png" },
    { name: "Caparo", country: "Reino Unido", logo: "./logos/caparo-logo.png" },
    { name: "Carlsson", country: "Alemania", logo: "./logos/carlsson-logo.png" },
    { name: "Caterham", country: "Reino Unido", logo: "./logos/caterham-logo.png" },
    { name: "Changan", country: "China", logo: "./logos/changan-logo.png" },
    { name: "Changfeng", country: "China", logo: "./logos/changfeng-logo.png" },
    { name: "Chery", country: "China", logo: "./logos/chery-logo.png" },
    { name: "Chevrolet", country: "Estados Unidos", logo: "./logos/chevrolet-logo.png" },
    { name: "Chrysler", country: "Estados Unidos", logo: "./logos/chrysler-logo.png" },
    { name: "Cisitalia", country: "Italia", logo: "./logos/cisitalia-logo.png" },
    { name: "Citroën", country: "Francia", logo: "./logos/citroen-logo.png" },
    { name: "Cizeta", country: "Italia", logo: "./logos/cizeta-logo.png" },
    { name: "Cole", country: "Estados Unidos", logo: "./logos/cole-logo.png" },
    { name: "Corre La Licorne", country: "Francia", logo: "./logos/corre-la-licorne-logo.png" },
    { name: "Corvette", country: "Estados Unidos", logo: "./logos/corvette-logo.png" },
    { name: "Dacia", country: "Rumania", logo: "./logos/dacia-logo.png" },
    { name: "Daewoo", country: "Corea del Sur", logo: "./logos/daewoo-logo.png" },
    { name: "DAF", country: "Países Bajos", logo: "./logos/daf-logo.png" },
    { name: "Daihatsu", country: "Japón", logo: "./logos/daihatsu-logo.png" },
    { name: "Daimler", country: "Reino Unido", logo: "./logos/daimler-logo.png" },
    { name: "Dartz", country: "Letonia", logo: "./logos/dartz-logo.png" },
    { name: "Datsun", country: "Japón", logo: "./logos/datsun-logo.png" },
    { name: "David Brown", country: "Reino Unido", logo: "./logos/david-brown-logo.png" },
    { name: "Dayun", country: "China", logo: "./logos/dayun-logo.png" },
    { name: "De Tomaso", country: "Italia", logo: "./logos/de-tomaso-logo.png" },
    { name: "Delage", country: "Francia", logo: "./logos/delage-logo.png" },
    { name: "DeLorean", country: "Estados Unidos", logo: "./logos/delorean-logo.png" },
    { name: "DeSoto", country: "Estados Unidos", logo: "./logos/desoto-logo.png" },
    { name: "Detroit Electric", country: "Estados Unidos", logo: "./logos/detroit-electric-logo.png" },
    { name: "Devel Sixteen", country: "Emiratos Árabes Unidos", logo: "./logos/devel-sixteen-logo.png" },
    { name: "Diatto", country: "Italia", logo: "./logos/diatto-logo.png" },
    { name: "Dina", country: "México", logo: "./logos/dina-logo.png" },
    { name: "DKW", country: "Alemania", logo: "./logos/dkw-logo.png" },
    { name: "Dodge", country: "Estados Unidos", logo: "./logos/dodge-logo.png" },
    { name: "Dodge Viper", country: "Estados Unidos", logo: "./logos/dodge-viper-logo.png" },
    { name: "Dongfeng", country: "China", logo: "./logos/dongfeng-logo.png" },
    { name: "Donkervoort", country: "Países Bajos", logo: "./logos/donkervoort-logo.png" },
    { name: "Drako", country: "Estados Unidos", logo: "./logos/drako-logo.png" },
    { name: "DS", country: "Francia", logo: "./logos/ds-logo.png" },
    { name: "Duesenberg", country: "Estados Unidos", logo: "./logos/duesenberg-logo.png" },
    { name: "Eagle", country: "Estados Unidos", logo: "./logos/eagle-logo.png" },
    { name: "EDAG", country: "Alemania", logo: "./logos/edag-logo.png" },
    { name: "Edsel", country: "Estados Unidos", logo: "./logos/edsel-logo.png" },
    { name: "Eicher", country: "India", logo: "./logos/eicher-logo.png" },
    { name: "Elemental", country: "Reino Unido", logo: "./logos/elemental-logo.png" },
    { name: "Elfin", country: "Australia", logo: "./logos/elfin-logo.png" },
    { name: "Elva", country: "Reino Unido", logo: "./logos/elva-logo.png" },
    { name: "Englon", country: "China", logo: "./logos/englon-logo.png" },
    { name: "ERF", country: "Reino Unido", logo: "./logos/erf-logo.png" },
    { name: "Eterniti", country: "Reino Unido", logo: "./logos/eterniti-logo.png" },
    { name: "Exeed", country: "China", logo: "./logos/exeed-logo.png" },
    { name: "Facel Vega", country: "Francia", logo: "./logos/facel-vega-logo.png" },
    { name: "Faraday Future", country: "Estados Unidos", logo: "./logos/faraday-future-logo.png" },
    { name: "FAW Jiefang", country: "China", logo: "./logos/faw-jiefang-logo.png" },
    { name: "FAW", country: "China", logo: "./logos/faw-logo.png" },
    { name: "Ferrari", country: "Italia", logo: "./logos/ferrari-logo.png" },
    { name: "Fiat", country: "Italia", logo: "./logos/fiat-logo.png" },
    { name: "Fioravanti", country: "Italia", logo: "./logos/fioravanti-logo.png" },
    { name: "Fisker", country: "Estados Unidos", logo: "./logos/fisker-logo.png" },
    { name: "Foden", country: "Reino Unido", logo: "./logos/foden-logo.png" },
    { name: "Force", country: "India", logo: "./logos/force-logo.png" },
    { name: "Ford", country: "Estados Unidos", logo: "./logos/ford-logo.png" },
    { name: "Ford Mustang", country: "Estados Unidos", logo: "./logos/ford-mustang-logo.png" },
    { name: "Foton", country: "China", logo: "./logos/foton-logo.png" },
    { name: "FPV", country: "Australia", logo: "./logos/fpv-logo.png" },
    { name: "Franklin", country: "Estados Unidos", logo: "./logos/franklin-logo.png" },
    { name: "Freightliner", country: "Estados Unidos", logo: "./logos/freightliner-logo.png" },
    { name: "FSO", country: "Polonia", logo: "./logos/fso-logo.png" },
    { name: "GAC", country: "China", logo: "./logos/gac-logo.png" },
    { name: "Gardner Douglas", country: "Reino Unido", logo: "./logos/gardner-douglas-logo.png" },
    { name: "GAZ", country: "Rusia", logo: "./logos/gaz-logo.png" },
    { name: "Geely", country: "China", logo: "./logos/geely-logo.png" },
    { name: "General Motors", country: "Estados Unidos", logo: "./logos/general-motors-logo.png" },
    { name: "Genesis", country: "Corea del Sur", logo: "./logos/genesis-logo.png" },
    { name: "Geo", country: "Estados Unidos", logo: "./logos/geo-logo.png" },
    { name: "Geometry", country: "China", logo: "./logos/geometry-logo.png" },
    { name: "Gilbern", country: "Reino Unido", logo: "./logos/gilbern-logo.png" },
    { name: "Gillet", country: "Bélgica", logo: "./logos/gillet-logo.png" },
    { name: "Ginetta", country: "Reino Unido", logo: "./logos/ginetta-logo.png" },
    { name: "GMC", country: "Estados Unidos", logo: "./logos/gmc-logo.png" },
    { name: "Golden Dragon", country: "China", logo: "./logos/golden-dragon-logo.png" },
    { name: "Gonow", country: "China", logo: "./logos/gonow-logo.png" },
    { name: "Great Wall", country: "China", logo: "./logos/great-wall-logo.png" },
    { name: "Grinnall", country: "Reino Unido", logo: "./logos/grinnall-logo.png" },
    { name: "Gumpert", country: "Alemania", logo: "./logos/gumpert-logo.png" },
    { name: "Hafei", country: "China", logo: "./logos/hafei-logo.png" },
    { name: "Haima", country: "China", logo: "./logos/haima-logo.png" },
    { name: "Haval", country: "China", logo: "./logos/haval-logo.png" },
    { name: "Hawtai", country: "China", logo: "./logos/hawtai-logo.png" },
    { name: "Hennessey", country: "Estados Unidos", logo: "./logos/hennessey-logo.png" },
    { name: "Higer", country: "China", logo: "./logos/higer-logo.png" },
    { name: "Hillman", country: "Reino Unido", logo: "./logos/hillman-logo.png" },
    { name: "Hindustan", country: "India", logo: "./logos/hindustan-logo.png" },
    { name: "Hino", country: "Japón", logo: "./logos/hino-logo.png" },
    { name: "HiPhi", country: "China", logo: "./logos/hiphi-logo.png" },
    { name: "Hispano-Suiza", country: "España", logo: "./logos/hispano-suiza-logo.png" },
    { name: "Holden", country: "Australia", logo: "./logos/holden-logo.png" },
    { name: "Hommell", country: "Francia", logo: "./logos/hommell-logo.png" },
    { name: "Honda", country: "Japón", logo: "./logos/honda-logo.png" },
    { name: "Hongqi", country: "China", logo: "./logos/hongqi-logo.png" },
    { name: "Hongyan", country: "China", logo: "./logos/hongyan-logo.png" },
    { name: "Horch", country: "Alemania", logo: "./logos/horch-logo.png" },
    { name: "HSV", country: "Australia", logo: "./logos/hsv-logo.png" },
    { name: "Hudson", country: "Estados Unidos", logo: "./logos/hudson-logo.png" },
    { name: "Hummer", country: "Estados Unidos", logo: "./logos/hummer-logo.png" },
    { name: "Hupmobile", country: "Estados Unidos", logo: "./logos/hupmobile-logo.png" },
    { name: "Hyundai", country: "Corea del Sur", logo: "./logos/hyundai-logo.png" },
    { name: "IC Bus", country: "Estados Unidos", logo: "./logos/ic-bus-logo.png" },
    { name: "Infiniti", country: "Japón", logo: "./logos/infiniti-logo.png" },
    { name: "Innocenti", country: "Italia", logo: "./logos/innocenti-logo.png" },
    { name: "Intermeccanica", country: "Canadá", logo: "./logos/intermeccanica-logo.png" },
    { name: "International Harvester", country: "Estados Unidos", logo: "./logos/international-harvester-logo.png" },
    { name: "International", country: "Estados Unidos", logo: "./logos/international-logo.png" },
    { name: "Iran Khodro", country: "Irán", logo: "./logos/iran-khodro-logo.png" },
    { name: "Irizar", country: "España", logo: "./logos/irizar-logo.png" },
    { name: "Isdera", country: "Alemania", logo: "./logos/isdera-logo.png" },
    { name: "Iso", country: "Italia", logo: "./logos/iso-logo.png" },
    { name: "Isuzu", country: "Japón", logo: "./logos/isuzu-logo.png" },
    { name: "Iveco", country: "Italia", logo: "./logos/iveco-logo.png" },
    { name: "JAC", country: "China", logo: "./logos/jac-logo.png" },
    { name: "Jaguar", country: "Reino Unido", logo: "./logos/jaguar-logo.png" },
    { name: "Jawa", country: "República Checa", logo: "./logos/jawa-logo.png" },
    { name: "JBA Motors", country: "Reino Unido", logo: "./logos/jba-motors-logo.png" },
    { name: "Jeep", country: "Estados Unidos", logo: "./logos/jeep-logo.png" },
    { name: "Jensen", country: "Reino Unido", logo: "./logos/jensen-logo.png" },
    { name: "Jetta", country: "China", logo: "./logos/jetta-logo.png" },
    { name: "Jiangling", country: "China", logo: "./logos/jiangling-logo.png" },
    { name: "Kaiser", country: "Estados Unidos", logo: "./logos/kaiser-logo.png" },
    { name: "Kamaz", country: "Rusia", logo: "./logos/kamaz-logo.png" },
    { name: "Karlmann King", country: "China", logo: "./logos/karlmann-king-logo.png" },
    { name: "Karma", country: "Estados Unidos", logo: "./logos/karma-logo.png" },
    { name: "Keating", country: "Reino Unido", logo: "./logos/keating-logo.png" },
    { name: "Kenworth", country: "Estados Unidos", logo: "./logos/kenworth-logo.png" },
    { name: "Kia", country: "Corea del Sur", logo: "./logos/kia-logo.png" },
    { name: "King Long", country: "China", logo: "./logos/king-long-logo.png" },
    { name: "Koenigsegg", country: "Suecia", logo: "./logos/koenigsegg-logo.png" },
    { name: "KTM", country: "Austria", logo: "./logos/ktm-logo.png" },
    { name: "Lada", country: "Rusia", logo: "./logos/lada-logo.png" },
    { name: "Lagonda", country: "Reino Unido", logo: "./logos/lagonda-logo.png" },
    { name: "Lamborghini", country: "Italia", logo: "./logos/lamborghini-logo.png" },
    { name: "Lancia", country: "Italia", logo: "./logos/lancia-logo.png" },
    { name: "Land Rover", country: "Reino Unido", logo: "./logos/land-rover-logo.png" },
    { name: "Landwind", country: "China", logo: "./logos/landwind-logo.png" },
    { name: "Laraki", country: "Marruecos", logo: "./logos/laraki-logo.png" },
    { name: "Leapmotor", country: "China", logo: "./logos/leapmotor-logo.png" },
    { name: "Lexus", country: "Japón", logo: "./logos/lexus-logo.png" },
    { name: "Leyland", country: "Reino Unido", logo: "./logos/leyland-logo.png" },
    { name: "Lifan", country: "China", logo: "./logos/lifan-logo.png" },
    { name: "Ligier", country: "Francia", logo: "./logos/ligier-logo.png" },
    { name: "Lincoln", country: "Estados Unidos", logo: "./logos/lincoln-logo.png" },
    { name: "Lister", country: "Reino Unido", logo: "./logos/lister-logo.png" },
    { name: "Li Auto", country: "China", logo: "./logos/lixiang-logo.png" },
    { name: "Lloyd", country: "Alemania", logo: "./logos/lloyd-logo.png" },
    { name: "Lobini", country: "Brasil", logo: "./logos/lobini-logo.png" },
    { name: "LEVC", country: "Reino Unido", logo: "./logos/london-ev-company-logo.png" },
    { name: "Lordstown", country: "Estados Unidos", logo: "./logos/lordstown-logo.png" },
    { name: "Lotus", country: "Reino Unido", logo: "./logos/lotus-logo.png" },
    { name: "Lucid", country: "Estados Unidos", logo: "./logos/lucid-logo.png" },
    { name: "Luxgen", country: "Taiwán", logo: "./logos/luxgen-logo.png" },
    { name: "Lynk & Co", country: "China", logo: "./logos/lynkco-logo.png" },
    { name: "Mack", country: "Estados Unidos", logo: "./logos/mack-logo.png" },
    { name: "Mahindra", country: "India", logo: "./logos/mahindra-logo.png" },
    { name: "MAN", country: "Alemania", logo: "./logos/man-logo.png" },
    { name: "Mansory", country: "Alemania", logo: "./logos/mansory-logo.png" },
    { name: "Marcos", country: "Reino Unido", logo: "./logos/marcos-logo.png" },
    { name: "Marlin", country: "Reino Unido", logo: "./logos/marlin-logo.png" },
    { name: "Maserati", country: "Italia", logo: "./logos/maserati-logo.png" },
    { name: "Mastretta", country: "México", logo: "./logos/mastretta-logo.png" },
    { name: "Maxus", country: "China", logo: "./logos/maxus-logo.png" },
    { name: "Maybach", country: "Alemania", logo: "./logos/maybach-logo.png" },
    { name: "MAZ", country: "Bielorrusia", logo: "./logos/maz-logo.png" },
    { name: "Mazda", country: "Japón", logo: "./logos/mazda-logo.png" },
    { name: "Mazzanti", country: "Italia", logo: "./logos/mazzanti-logo.png" },
    { name: "McLaren", country: "Reino Unido", logo: "./logos/mclaren-logo.png" },
    { name: "Melkus", country: "Alemania", logo: "./logos/melkus-logo.png" },
    { name: "Mercedes-AMG", country: "Alemania", logo: "./logos/mercedes-amg-logo.png" },
    { name: "Mercedes-Benz", country: "Alemania", logo: "./logos/mercedes-benz-logo.png" },
    { name: "Mercury", country: "Estados Unidos", logo: "./logos/mercury-logo.png" },
    { name: "Merkur", country: "Alemania", logo: "./logos/merkur-logo.png" },
    { name: "MEV", country: "Reino Unido", logo: "./logos/mev-logo.png" },
    { name: "MG", country: "Reino Unido", logo: "./logos/mg-logo.png" },
    { name: "Microcar", country: "Francia", logo: "./logos/microcar-logo.png" },
    { name: "Mini", country: "Reino Unido", logo: "./logos/mini-logo.png" },
    { name: "Mitsubishi", country: "Japón", logo: "./logos/mitsubishi-logo.png" },
    { name: "Mitsuoka", country: "Japón", logo: "./logos/mitsuoka-logo.png" },
    { name: "MK Sportscars", country: "Reino Unido", logo: "./logos/mk-sportscars-logo.png" },
    { name: "Morgan", country: "Reino Unido", logo: "./logos/morgan-logo.png" },
    { name: "Morris", country: "Reino Unido", logo: "./logos/morris-logo.png" },
    { name: "Mosler", country: "Estados Unidos", logo: "./logos/mosler-logo.png" },
    { name: "Navistar", country: "Estados Unidos", logo: "./logos/navistar-logo.png" },
    { name: "NEVS", country: "Suecia", logo: "./logos/nevs-logo.png" },
    { name: "Nikola", country: "Estados Unidos", logo: "./logos/nikola-logo.png" },
    { name: "NIO", country: "China", logo: "./logos/nio-logo.png" },
    { name: "Nissan GT-R", country: "Japón", logo: "./logos/nissan-gt-r-logo.png" },
    { name: "Nissan", country: "Japón", logo: "./logos/nissan-logo.png" },
    { name: "Nissan Nismo", country: "Japón", logo: "./logos/nissan-nismo-logo.png" },
    { name: "Noble", country: "Reino Unido", logo: "./logos/noble-logo.png" },
    { name: "Oldsmobile", country: "Estados Unidos", logo: "./logos/oldsmobile-logo.png" },
    { name: "Oltcit", country: "Rumania", logo: "./logos/oltcit-logo.png" },
    { name: "Opel", country: "Alemania", logo: "./logos/opel-logo.png" },
    { name: "OSCA", country: "Italia", logo: "./logos/osca-logo.png" },
    { name: "PACCAR", country: "Estados Unidos", logo: "./logos/paccar-logo.png" },
    { name: "Packard", country: "Estados Unidos", logo: "./logos/packard-logo.png" },
    { name: "Pagani", country: "Italia", logo: "./logos/pagani-logo.png" },
    { name: "Panhard", country: "Francia", logo: "./logos/panhard-logo.png" },
    { name: "Panoz", country: "Estados Unidos", logo: "./logos/panoz-logo.png" },
    { name: "Pegaso", country: "España", logo: "./logos/pegaso-logo.png" },
    { name: "Perodua", country: "Malasia", logo: "./logos/perodua-logo.png" },
    { name: "Peterbilt", country: "Estados Unidos", logo: "./logos/peterbilt-logo.png" },
    { name: "Peugeot", country: "Francia", logo: "./logos/peugeot-logo.png" },
    { name: "PGO", country: "Francia", logo: "./logos/pgo-logo.png" },
    { name: "Pierce-Arrow", country: "Estados Unidos", logo: "./logos/pierce-arrow-logo.png" },
    { name: "Pininfarina", country: "Italia", logo: "./logos/pininfarina-logo.png" },
    { name: "Plymouth", country: "Estados Unidos", logo: "./logos/plymouth-logo.png" },
    { name: "Polestar", country: "Suecia", logo: "./logos/polestar-logo.png" },
    { name: "Pontiac", country: "Estados Unidos", logo: "./logos/pontiac-logo.png" },
    { name: "Porsche", country: "Alemania", logo: "./logos/porsche-logo.png" },
    { name: "Praga", country: "República Checa", logo: "./logos/praga-logo.png" },
    { name: "Premier", country: "India", logo: "./logos/premier-logo.png" },
    { name: "Prodrive", country: "Reino Unido", logo: "./logos/prodrive-logo.png" },
    { name: "Proton", country: "Malasia", logo: "./logos/proton-logo.png" },
    { name: "Qoros", country: "China", logo: "./logos/qoros-logo.png" },
    { name: "Radical", country: "Reino Unido", logo: "./logos/radical-logo.png" },
    { name: "Ram", country: "Estados Unidos", logo: "./logos/ram-logo.png" },
    { name: "Rambler", country: "Estados Unidos", logo: "./logos/rambler-logo.png" },
    { name: "Ranz", country: "China", logo: "./logos/ranz-logo.png" },
    { name: "Renault", country: "Francia", logo: "./logos/renault-logo.png" },
    { name: "Renault Samsung", country: "Corea del Sur", logo: "./logos/renault-samsung-logo.png" },
    { name: "Rezvani", country: "Estados Unidos", logo: "./logos/rezvani-logo.png" },
    { name: "Riley", country: "Reino Unido", logo: "./logos/riley-logo.png" },
    { name: "Rimac", country: "Croacia", logo: "./logos/rimac-logo.png" },
    { name: "Rinspeed", country: "Suiza", logo: "./logos/rinspeed-logo.png" },
    { name: "Rivian", country: "Estados Unidos", logo: "./logos/rivian-logo.png" },
    { name: "Roewe", country: "China", logo: "./logos/roewe-logo.png" },
    { name: "Rolls-Royce", country: "Reino Unido", logo: "./logos/rolls-royce-logo.png" },
    { name: "Ronart", country: "Reino Unido", logo: "./logos/ronart-logo.png" },
    { name: "Rossion", country: "Estados Unidos", logo: "./logos/rossion-logo.png" },
    { name: "Rover", country: "Reino Unido", logo: "./logos/rover-logo.png" },
    { name: "Ruf", country: "Alemania", logo: "./logos/ruf-logo.png" },
    { name: "Saab", country: "Suecia", logo: "./logos/saab-logo.png" },
    { name: "SAIC", country: "China", logo: "./logos/saic-logo.png" },
    { name: "Saipa", country: "Irán", logo: "./logos/saipa-logo.png" },
    { name: "Saleen", country: "Estados Unidos", logo: "./logos/saleen-logo.png" },
    { name: "Saturn", country: "Estados Unidos", logo: "./logos/saturn-logo.png" },
    { name: "Scania", country: "Suecia", logo: "./logos/scania-logo.png" },
    { name: "Scion", country: "Japón", logo: "./logos/scion-logo.png" },
    { name: "SEAT", country: "España", logo: "./logos/seat-logo.png" },
    { name: "Setra", country: "Alemania", logo: "./logos/setra-logo.png" },
    { name: "Shacman", country: "China", logo: "./logos/shacman-logo.png" },
    { name: "Simca", country: "Francia", logo: "./logos/simca-logo.png" },
    { name: "Singer", country: "Estados Unidos", logo: "./logos/singer-logo.png" },
    { name: "Singulato", country: "China", logo: "./logos/singulato-logo.png" },
    { name: "Sinotruk", country: "China", logo: "./logos/sinotruk-logo.png" },
    { name: "Sisu", country: "Finlandia", logo: "./logos/sisu-logo.png" },
    { name: "Škoda", country: "República Checa", logo: "./logos/skoda-logo.png" },
    { name: "Smart", country: "Alemania", logo: "./logos/smart-logo.png" },
    { name: "Soueast", country: "China", logo: "./logos/soueast-logo.png" },
    { name: "Spania GTA", country: "España", logo: "./logos/spania-gta-logo.png" },
    { name: "Spirra", country: "Corea del Sur", logo: "./logos/spirra-logo.png" },
    { name: "Spyker", country: "Países Bajos", logo: "./logos/spyker-logo.png" },
    { name: "SsangYong", country: "Corea del Sur", logo: "./logos/ssangyong-logo.png" },
    { name: "SSC", country: "Estados Unidos", logo: "./logos/ssc-logo.png" },
    { name: "Stellantis", country: "Países Bajos", logo: "./logos/stellantis-logo.png" },
    { name: "Sterling", country: "Estados Unidos", logo: "./logos/sterling-logo.png" },
    { name: "Studebaker", country: "Estados Unidos", logo: "./logos/studebaker-logo.png" },
    { name: "Stutz", country: "Estados Unidos", logo: "./logos/stutz-logo.png" },
    { name: "Subaru", country: "Japón", logo: "./logos/subaru-logo.png" },
    { name: "Suffolk", country: "Reino Unido", logo: "./logos/suffolk-logo.png" },
    { name: "Suzuki", country: "Japón", logo: "./logos/suzuki-logo.png" },
    { name: "Talbot", country: "Reino Unido", logo: "./logos/talbot-logo.png" },
    { name: "Tata", country: "India", logo: "./logos/tata-logo.png" },
    { name: "Tatra", country: "República Checa", logo: "./logos/tatra-logo.png" },
    { name: "Tauro Sport Auto", country: "España", logo: "./logos/tauro-sport-auto-logo.png" },
    { name: "TechArt", country: "Alemania", logo: "./logos/techart-logo.png" },
    { name: "Tesla", country: "Estados Unidos", logo: "./logos/tesla-logo.png" },
    { name: "Toyota Alphard", country: "Japón", logo: "./logos/toyota-alphard-logo.png" },
    { name: "Toyota Century", country: "Japón", logo: "./logos/toyota-century-logo.png" },
    { name: "Toyota Crown", country: "Japón", logo: "./logos/toyota-crown-logo.png" },
    { name: "Toyota", country: "Japón", logo: "./logos/toyota-logo.png" },
    { name: "Tramontana", country: "España", logo: "./logos/tramontana-logo.png" },
    { name: "Trion", country: "Estados Unidos", logo: "./logos/trion-logo.png" },
    { name: "Triumph", country: "Reino Unido", logo: "./logos/triumph-logo.png" },
    { name: "Troller", country: "Brasil", logo: "./logos/troller-logo.png" },
    { name: "Tucker", country: "Estados Unidos", logo: "./logos/tucker-logo.png" },
    { name: "TVR", country: "Reino Unido", logo: "./logos/tvr-logo.png" },
    { name: "UAZ", country: "Rusia", logo: "./logos/uaz-logo.png" },
    { name: "UD Trucks", country: "Japón", logo: "./logos/ud-trucks-logo.png" },
    { name: "Ultima", country: "Reino Unido", logo: "./logos/ultima-logo.png" },
    { name: "Vandenbrink", country: "Países Bajos", logo: "./logos/vandenbrink-logo.png" },
    { name: "Vauxhall", country: "Reino Unido", logo: "./logos/vauxhall-logo.png" },
    { name: "Vector", country: "Estados Unidos", logo: "./logos/vector-logo.png" },
    { name: "Vencer", country: "Países Bajos", logo: "./logos/vencer-logo.png" },
    { name: "Venturi", country: "Mónaco", logo: "./logos/venturi-logo.png" },
    { name: "Venucia", country: "China", logo: "./logos/venucia-logo.png" },
    { name: "VinFast", country: "Vietnam", logo: "./logos/vinfast-logo.png" },
    { name: "VLF", country: "Estados Unidos", logo: "./logos/vlf-logo.png" },
    { name: "Volkswagen", country: "Alemania", logo: "./logos/volkswagen-logo.png" },
    { name: "Volvo", country: "Suecia", logo: "./logos/volvo-logo.png" },
    { name: "W Motors", country: "Emiratos Árabes Unidos", logo: "./logos/w-motors-logo.png" },
    { name: "Wanderer", country: "Alemania", logo: "./logos/wanderer-logo.png" },
    { name: "Wartburg", country: "Alemania", logo: "./logos/wartburg-logo.png" },
    { name: "Weltmeister", country: "China", logo: "./logos/weltmeister-logo.png" },
    { name: "Western Star", country: "Estados Unidos", logo: "./logos/western-star-logo.png" },
    { name: "Westfield", country: "Reino Unido", logo: "./logos/westfield-logo.png" },
    { name: "WEY", country: "China", logo: "./logos/wey-logo.png" },
    { name: "Wiesmann", country: "Alemania", logo: "./logos/wiesmann-logo.png" },
    { name: "Willys-Overland", country: "Estados Unidos", logo: "./logos/willys-overland-logo.png" },
    { name: "Workhorse", country: "Estados Unidos", logo: "./logos/workhorse-logo.png" },
    { name: "Wuling", country: "China", logo: "./logos/wuling-logo.png" },
    { name: "XPeng", country: "China", logo: "./logos/xpeng-logo.png" },
    { name: "Yulon", country: "Taiwán", logo: "./logos/yulon-logo.png" },
    { name: "Yutong", country: "China", logo: "./logos/yutong-logo.png" },
    { name: "Zarooq", country: "Emiratos Árabes Unidos", logo: "./logos/zarooq-logo.png" },
    { name: "Zastava", country: "Serbia", logo: "./logos/zastava-logo.png" },
    { name: "ZAZ", country: "Ucrania", logo: "./logos/zaz-logo.png" },
    { name: "Zeekr", country: "China", logo: "./logos/zeekr-logo.png" },
    { name: "Zenos", country: "Reino Unido", logo: "./logos/zenos-logo.png" },
    { name: "Zenvo", country: "Dinamarca", logo: "./logos/zenvo-logo.png" },
    { name: "Zinoro", country: "China", logo: "./logos/zhinuo-logo.png" },
    { name: "Zhongtong", country: "China", logo: "./logos/zhongtong-logo.png" },
    { name: "Zotye", country: "China", logo: "./logos/zotye-logo.png" }
];
